name: "Deploy Zup"
description: "Deploys a Zup to Zuplo"

inputs:
  project:
    description: "The project name"
    required: true
  environment:
    description: "The environment to deploy. Usually 'staging' or 'production'"
    required: false
    default: "production"

runs:
  using: "node16"
  main: "index.js"
