name: "Deploy Zup"
description: "Deploys a Zup to Zuplo"

inputs:
  project:
    description: "The project name"
    required: true
  environment:
    description: "The environment to deploy. Usually 'staging' or 'production'"
    required: false
    default: "production"
  account_id:
    description: "The cloudflare account ID"
    required: true
  api_token:
    description: "The cloudflare API Token"
    required: true

runs:
  using: "node16"
  main: "./dist/index.js"
